// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvYRsG3xgrRXpK6da2pE6pDUym08DwOmo',
    appId: '1:1044984608295:web:e6f97fc6be4c69ff430002',
    messagingSenderId: '1044984608295',
    projectId: 'sdl-hackathon-869ac',
    authDomain: 'sdl-hackathon-869ac.firebaseapp.com',
    storageBucket: 'sdl-hackathon-869ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTUb1qtr2cYauQSrG_E1CSeOtyikjzOD8',
    appId: '1:1044984608295:android:87dc62b7594a78db430002',
    messagingSenderId: '1044984608295',
    projectId: 'sdl-hackathon-869ac',
    storageBucket: 'sdl-hackathon-869ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0oC5uoWVQZNnRN-Art_vD6NwpG3qrHIE',
    appId: '1:1044984608295:ios:69992b964637c0fa430002',
    messagingSenderId: '1044984608295',
    projectId: 'sdl-hackathon-869ac',
    storageBucket: 'sdl-hackathon-869ac.appspot.com',
    iosBundleId: 'com.example.sdlHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0oC5uoWVQZNnRN-Art_vD6NwpG3qrHIE',
    appId: '1:1044984608295:ios:69992b964637c0fa430002',
    messagingSenderId: '1044984608295',
    projectId: 'sdl-hackathon-869ac',
    storageBucket: 'sdl-hackathon-869ac.appspot.com',
    iosBundleId: 'com.example.sdlHackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvYRsG3xgrRXpK6da2pE6pDUym08DwOmo',
    appId: '1:1044984608295:web:b6c34cd0945168bf430002',
    messagingSenderId: '1044984608295',
    projectId: 'sdl-hackathon-869ac',
    authDomain: 'sdl-hackathon-869ac.firebaseapp.com',
    storageBucket: 'sdl-hackathon-869ac.appspot.com',
  );
}
